In [29]:
total_amount = 0
items = []

customer = input("Customer Name: ")

while True:
    name = input("Item Name: ")
    qty = int(input("Quantity: "))
    price = float(input("Price per item: "))
    total = qty * price
    items.append((name, qty, price, total))
    total_amount += total

    more = input("Add more items? (y/n): ")
    if more.lower() != 'y':
        break

print("\n==== BILL ====")
print(f"Customer: {customer}")
print("Item        Qty  Price  Total")
for name, qty, price, total in items:
    print(f"{name:<10} {qty:<4} ₹{price:<6} ₹{total}")
print("-----------------------")
print(f"Total Amount: ₹{total_amount}")


Customer Name:  ankit
Item Name:  kurkure
Quantity:  2
Price per item:  12
Add more items? (y/n):  n



==== BILL ====
Customer: ankit
Item        Qty  Price  Total
kurkure    2    ₹12.0   ₹24.0
-----------------------
Total Amount: ₹24.0


In [1]:
import numpy as np 
a=np.array([1,2,3])
b=np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [4]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)


(2, 3)
6
2
int64


In [10]:
arr=np.array([10,20,30,40,50,60])
print(arr.reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [16]:
arr=np.array([10,20,30,40,50,60])
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3,3))
print(np.full((2,2),7))
print(np.arange(1,10,2))
print(np.linspace(1,5,4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 3 5 7 9]
[1.         2.33333333 3.66666667 5.        ]


In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a + b)
print(a * b)
print(a ** b)
print(np.sqrt(a))
print(np.mean(a))

[5 7 9]
[ 4 10 18]
[  1  32 729]
[1.         1.41421356 1.73205081]
2.0


In [19]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(a.T)

21
1
6
[5 7 9]
[ 6 15]
[[1 4]
 [2 5]
 [3 6]]
